apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: javabase
  namespace: javabase
  labels:
    app.kubernetes.io/name: javabase
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: javabase
